version: '3.4'

services:
  sampleapp.mssqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sampleapp.mssqlserver
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=${MSSQLSERVER_PWD}
        - MSSQL_PID=Express
    mem_limit: 3048M
    mem_reservation: 512M
    ports:
        - 1433:1433
    networks: 
        - sample-app

  sampleapp.identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    container_name: sampleapp.identity.api
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_SERVER=sampleapp.mssqlserver
      - DB_PORT=1433
      - DATABASE=IdentityServerDB
      - DB_USER=${MSSQLSERVER_UNAME}
      - DB_PASSWORD=${MSSQLSERVER_PWD}
    ports:
      - 8080:80
    depends_on:
      - "sampleapp.mssqlserver"
    networks: 
        - sample-app
    restart: always

networks: 
  sample-app:
    driver: bridge
